name: Microbench

on:
  push:
  
jobs:
  Microbench:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    
    - name: install dependencies
      run: |
        sudo apt install build-essential git m4 scons zlib1g zlib1g-dev \
          libprotobuf-dev protobuf-compiler libprotoc-dev libgoogle-perftools-dev \
          python3-dev python-is-python3 libboost-all-dev pkg-config gcc-10 g++-10 \
          python3-tk
    
    - name: clone microbench
      run: git clone https://github.com/VerticalResearchGroup/microbench.git
    
    - name: build microbench
      run: |
        cd microbench
        make
    
    - name: build gem5
      run: scons build/X86/gem5.opt -j 8
    
    - name: benchmark
      run: python3 microbench_branch_predictor.py

    - uses: actions/upload-artifact@v4
      with:
        name: stats
        path: ./out/
